### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by SunYiZheXinKe** [SunYiZheXinKe/cppjs#1]
- [ ] Add Integer and Real type
- [ ] Add List type
- [ ] Add Method type, that automatically passes `self` as first argument
